import type { Metadata } from "next";

export const metadata: Metadata = { title: "Study Diagrams" };

// The study-diagrams dashboard is a prebuilt static site (public/diagrams/, generated by
// scripts/build_study_diagrams_site.py). Embedding it here means it lives INSIDE the app shell, so it
// shares the real NavBar (name, alerts, admin, all links) instead of the old standalone page that lost
// them. Internal links/assets are absolute (/diagrams/*) and navigate within the iframe; the app nav
// stays put above it. flex-1 + min-h-0 lets the iframe fill the viewport below the NavBar (and adjusts
// automatically if the API-key banner is showing).
export default function DiagramsPage() {
  return (
    <div className="flex-1 min-h-0">
      <iframe
        src="/diagrams/index.html"
        title="MW Study Diagrams"
        className="block w-full h-full border-0"
      />
    </div>
  );
}
