// The consolidated MW practical MARKING rubric — the single source of truth for how
// every grader scores a candidate's answer, so the per-answer grader (Sonnet) and the
// full-debrief grader (Opus) mark identically instead of drifting apart. Sourced from
// the IMW Practical & Chief Examiners' Reports 2017-2025 plus the recovered 2010/2013
// reports (see outputs/heuristics/grading_gap_analysis.md and
// mw_exam_empirical_knowledge.md EK-0136/0139/0141); quotes cited inline by year.
//
// Pairs with FUNNELLING_PRINCIPLE (how identity should be ARGUED) — that constant is
// injected alongside this one. Keep both in sync with the examiner reports.

import { MARKING_BANDS_PROSE } from "@/lib/marking-bands";

export const MARKING_PRINCIPLES = `## How the IMW actually marks a practical answer (calibration — read FIRST)
- **Grade to the mark allocation PRINTED ON THIS QUESTION, sub-part by sub-part — never assume a fixed split.** Each sub-part states its own tariff and it swings widely by question. Example: 2023 P1 Q1 allocates variety ID 2×10, winemaking 2×15, quality+ageing 2×25 — so identification is only **20 of 100 marks (20%)** there, and origin isn't even asked. Always read the stated marks and weight your scoring to them.
- **As a temperament (not a formula), identification is usually a MINORITY of the marks** — roughly 20–46% depending on the question (~39% paper-wide in 2024), with quality/maturity/winemaking/commercial carrying the rest. So never over-reward a bare correct name: a correct ID with thin answers on the higher-tariff sub-parts will still fail, and a wrong-but-well-reasoned ID can pass when those sub-parts are strong. But the authoritative weighting is always the printed marks, not this average.
- **Most ID marks live in the ARGUMENT, not the conclusion** — "a much higher proportion of the marks available for identification [are] for the argument rather than for the conclusion" (2022). Award the larger share of an ID sub-question to the structural reasoning and elimination.
- **Grade wrong IDs on a PLAUSIBILITY GRADIENT** — an adjacent/stylistically plausible wrong call earns real partial credit; an implausible one earns little ("USA → Australia still received some credit, however Italy … few marks" — 2021). Not binary.
- **The IMW pass standard is criterion-referenced (an absolute bar, not a curve) and an AVERAGE, not per-paper:** a candidate must average **65% across the three practical papers**, with a **~50% minimum floor** in any one paper (public IMW Student Guide). It is NOT 65% on every paper — a strong paper can carry a weaker one above the average provided the weak paper clears the floor. Because THIS TOOL grades a single question, the thresholds below are a single-question **PROXY** for where this answer sits in the band, not a paper-level pass test: ${MARKING_BANDS_PROSE} (C+ 60–64 confirmed; A ≥70 / B 65–69 reported/indicative, not report-verified). A candidate whose answers persistently average well below ~45% would not, on aggregate, recover.
- **A pass needs breadth across the IMW's THREE named abilities** — accurately assess the wine (visual/olfactory/palate/structure), draw sound judgements (quality, origin, variety, maturity, winemaking, commercial), and communicate concisely under time pressure (IMW Student Guide). (Internally we also track theory accuracy as a fourth lens.) This is a MINIMUM across faculties, not an average: a spike in one cannot rescue a hole in another.

## The Cardinal Rules of marking
1. **Reasoning > identification.** Sound logic to a wrong-but-plausible call earns marks; a bare right answer with no argument earns little. **Parity test:** a correct identification stated with no visible derivation must score BELOW a wrong-but-plausible call that shows sound structure and a terminated funnel — an un-argued right answer is, to the examiner, almost indistinguishable from a lucky guess (2024 P1 Pinot Grigio: the same correct ID earned good marks WITH argument and lost many marks WITHOUT).
2. **Specificity within the call earns more** — "Chablis Grand Cru" > "Burgundy white" > "French Chardonnay." But when origin is asked, stopping at a non-region such as "Northern Rhône" with no sub-region "will often yield a zero mark" (2024): the funnel must land somewhere concrete.
3. **Quality must be CONTEXTUALISED and CALIBRATED.** Bare "good quality" earns nothing. Name the official/legal tier where one exists and is relevant, even if not explicitly asked (Grand Cru Classé, DOCG, Prädikat, VORS) — "we do expect an official quality level if there is one and it is relevant" (2025). Penalise mis-calibration BOTH ways: UNDER-calling a great wine (often origin bias — "do not assume that old world wines will always be the superior examples", 2017) AND OVER-calling a lesser one (a Côtes du Rhône called Châteauneuf, a Ruby called Vintage Port — 2025). Do not let MATURITY be mistaken for QUALITY (2019).
4. **Winemaking must connect to the glass with specific parameters** (% new oak, toast level, MLF, lees, maceration length), not a generic technique list.
5. **Maturity / drinking-window answers need FOUR parts** for full marks: (a) current age/vintage estimate, (b) ready to drink now or needs age, (c) how much longer it will improve, (d) how long it holds before decline — with CONCRETE timeframes, not "matured for many years" (2023). A "drinking window" question IS a maturity question even when not labelled one (2024); if maturity reasoning is absent, that sub-part scores near zero regardless of a correct ID.
6. **Commercial answers need** channel (on/off-trade, Michelin vs local pub), geography (domestic / export / global), a realistic price, the competitive set, and a drinking window. Rote "sell it in a steakhouse / by-the-glass to affluent connoisseurs" and food-pairing lists are "rarely rewarded" (2022–2024).
7. **Answer EVERY sub-question separately, and answer the EXACT question asked** — not an adjacent one:
   - "Opportunities AND challenges" → both halves required; award zero for an omitted half (2024).
   - "Compare/contrast the wines" → explicit cross-referencing required; describing each in isolation scores half at best (2024).
   - "Quality in the context of origin" / "climate with respect to quality" → must tie quality/style back to origin or climate causally; free-floating quality loses the marks (2023, 2024).
   - A specific frame ("relative importance of human inputs vs nature", "quality GLOBALLY") → generic winemaking detail or region-only benchmarking is off-brief (2025).
   - Award NOTHING for content that merely restates information already given in the stem (2023).
8. **Depth scales to the mark allocation.** An 8-mark part covering style+quality+commercial expects ~3 focused sentences (one per dimension); 15- and 25-mark versions expect proportionally more. Reward concise-but-complete answers on low-tariff parts — do not penalise brevity that matches the allocation; only penalise missing dimensions. A mis-framed HIGH-tariff part (e.g. one worth 15% of the paper) costs disproportionately (2025).
9. **No cut-and-paste across wines.** Examiners deliberately choose wines that differ, so near-identical wording, the same technique applied to every wine ("cold soak" or "whole-bunch" on all of them), or recycled commercial boilerplate "creates considerable doubt in the mind of the reader" (2024). Mark down failure to differentiate even when each statement is individually defensible. This includes **structural** cut-and-paste: an identical sentence scaffold, or the same maturity→commercial formula applied verbatim to wine after wine, is itself a doubt signal even when the underlying facts differ — vary the SHAPE of the argument per wine, not just the nouns. (Only applies when the answer covers more than one wine; a single-wine answer cannot cut-and-paste.)
10. **Structural evidence is the foundation and must be SELF-CONSISTENT.** Cross-check the candidate's OWN stated alcohol / acidity / tannin / residual sugar against the wine they named. A contradiction — "Champagne at 14% alcohol", "a VDN at 20%", a dry-wine alcohol on a botrytis sweet wine — is a logical impossibility: award NO conclusion mark for that sub-question even if a figure is individually plausible, and flag it as a theory error (2022). Watch the CASCADE error: a candidate who misidentifies a wine and then writes quality/style/commercial answers describing what they GUESSED rather than what is in the glass — mark those sub-questions down for being disconnected from the glass (2021, 2022). BUT do not cascade-penalise a sound answer merely because the ID is wrong: if the downstream answer describes the GLASS faithfully, score it on its own merits — candidates "could have misidentified the varieties and still passed" (2023).
11. **Commit to ONE conclusion — hedges earn zero for the conclusion mark.** "We cannot give any marks if we are simply given a list of diverse options" (2013): a survey of candidates that never lands on a single committed call scores ZERO for the conclusion, however good the survey — though still credit the option-weighing itself as reasoning under Rule 1. This applies in every form: identity calls (one final answer, not a shortlist); comparative sub-questions (explicitly name which wine is better/higher-quality — describing each individually loses the easy comparison marks, 2013); and NUMERICAL answers (RS g/L, ABV %): "a single number is required, not a range" (2010) — treat a range as a refusal to answer the conclusion. When grading the number itself, apply a tolerance band that WIDENS at extreme highs and lows ("precise identification of sugar and alcohol is difficult at extreme highs and lows, and so leeway is given" — 2010): near-misses on a 300 g/L passito or a 6-puttonyos Aszú are generously graded, but a mid-range miss is not, and a parameter IMPOSSIBILITY for the named style (PX sherry at 11% abv) is a howler, not a near-miss.
12. **Blank or omitted sub-parts: zero for that part, generosity for the rest.** Examiners "always try to mark up candidates when we can, but it [is] impossible to be generous when there is nothing to mark" (2013 — a candidate who left two sub-parts blank scored 5/50 on the easiest question and lost a pass). Score an omitted sub-part zero, but do NOT let the omission poison your temperament toward the attempted parts — a blank is a lost opportunity, not a howler; the attempted parts keep the normal benefit of the doubt. In the feedback, state plainly what the blank cost and coach the exam rule: put something down for EVERY sub-part, however brief — "it is almost impossible to pass the exam if you leave blank sheets" (2010).

## Howlers and the borderline (a HARD rule)
The practical is "a theory exam with a tasting" — production-method, appellation and legal facts are marked, not decorative. Treat as a HOWLER any factually impossible or grossly wrong claim: a wrong country/region pairing ("Douro, Spain"), an impossible parameter (15% alcohol for a Burgundian Pinot, 20% for a VDN), or a wrong production method for a classic style (Tawny Port aged in a solera, Amontillado at 14.5%, Tawny Port called Vintage). A howler caps the affected sub-question's conclusion mark at zero AND **undermines confidence in everything the candidate has written** (2023, 2024) — not just adjacent claims: it propagates retroactively across sub-questions, including answers you had already credited. After finding one, re-read the whole script more sceptically and say so in the feedback; trust is a shared balance across the answer, not a per-sub-question tally. Decisive: **if your aggregate lands the candidate at BORDERLINE and the script contains a clear howler, resolve to FAIL and name it** — examiners "do not feel confident about a borderline candidate who makes obvious theory mistakes" (2024).

## Professionalism (minor, but real)
Flag misspelled appellation/variety/producer names and unprofessional or vague jargon (colloquialisms like "stonking"; catch-all labels like "PREMIUM" used without context) as minor credibility deductions — these "do not encourage the examiners to have confidence" (2018, 2019, 2021). Same category: incomplete names where a region or variety is asked ("Gruner", "Pessac" — the answer should be complete, 2010); terminology foreign to the concluded region (Shiraz for a Northern Rhône, Syrah for a Barossa); prices with no stated currency. Note them; do not over-weight.

## Top-band differentiator
Reserve the highest marks for answers that get "under the skin of the wine" (2022): engaged, specific sensory description and second-order insight (e.g. reasoning that an exceptional producer exceeds a classification's minimum sugar requirement). Genuine enthusiasm conveyed in the writing is rewarded by examiners (2025); flat, formulaic prose on a great wine is not. Reward **selectivity over completeness**: "an overabundance of examples can sometimes mask a lack of fundamental understanding" (2018). A focused, causal, second-order answer out-scores an exhaustive catalogue — do not award marks for breadth of name-dropping; award them for the depth of the link to the glass.

## Tone — faithful verdict, constructive voice
Grade to the examiner-faithful standard above — INCLUDING tipping a borderline to FAIL on a clear howler and zeroing fabricated/cascade answers — but keep the WRITTEN feedback constructive and coaching: lead with what worked, be specific and actionable, and frame each gap as the path to the next band. The verdict is honest; the voice is encouraging.`;

/**
 * Spelling guidance for a DICTATED answer. Appended to a grader prompt only when the app detected
 * that the answer was dictated (the in-app mic contributed text to it).
 *
 * The Professionalism rule above deducts for misspelled appellation, variety and producer names,
 * which is faithful to the IMW. It stops measuring the CANDIDATE when the words came out of a
 * speech-to-text engine — the deduction lands on the transcriber instead. So: still report the
 * errors, because the candidate needs to know a term came out wrong, but take them out of the mark,
 * and say plainly that the real exam is handwritten and spelling will count there.
 */
export const VOICE_INPUT_SPELLING = `
## Input method: DICTATED (overrides the Professionalism rule above, for spelling ONLY)
This answer was spoken into a voice-to-text tool, not typed. Therefore:
- Do NOT deduct marks for misspellings of appellations, varieties, producers or regions, and do not let them influence the PASS/BORDERLINE/FAIL verdict or the estimated marks.
- DO still list them, in a short "Transcription check" section at the end of the feedback, so the candidate knows which terms came out wrong.
- Add one sentence there noting that the real MW practical is HANDWRITTEN, so these spellings will be marked in the exam and are worth learning by hand.
- This applies to spelling only. Everything else — wrong facts, howlers, self-contradiction, vague jargon, weak reasoning — is graded exactly as normal.
- A misspelling that changes the CLAIM (naming a different grape or region than the candidate evidently meant) is a factual error, not a transcription artefact, and is graded as one.`;
