from __future__ import annotations

from pathlib import Path
from urllib.parse import quote_plus


ROOT = Path(__file__).resolve().parent.parent
RESEARCH_DIR = ROOT / "data" / "wine_research"


ENTRIES = {
    "2011_p3_w1": {
        "producer": "Taittinger",
        "wine_name": "Comtes de Champagne Blanc de Blancs",
        "country": "France",
        "region": "Champagne",
        "sub_region": "Champagne",
        "appellation": "Champagne",
        "classification": "Prestige cuvée Blanc de Blancs",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "100% Chardonnay",
        "technical": "Traditional-method Champagne from top Chardonnay villages, long lees ageing, prestige-cuvée positioning.",
        "quick": "Mature prestige Blanc de Blancs Champagne should show fine mousse, lemon curd, toast, chalk and a long autolytic finish. The palate is dry, precise and layered, with more persistence and complexity than a standard non-vintage brut.",
        "producer_style": "Taittinger is one of Champagne's major houses and Comtes de Champagne is its flagship Blanc de Blancs, prized for elegance, chalky finesse and extended lees ageing.",
        "why": "In 2011 Paper 3 this forms the top half of the Champagne pair. The point is to compare a mature prestige Blanc de Blancs against a simpler NV brut from the same region and judge method, quality and commercial standing.",
    },
    "2011_p3_w2": {
        "producer": "De Laurency",
        "wine_name": "Brut",
        "country": "France",
        "region": "Champagne",
        "sub_region": "Champagne",
        "appellation": "Champagne",
        "classification": "Non-vintage brut Champagne",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "Likely classic Champagne blend",
        "technical": "Traditional-method Champagne, likely multi-vintage blending with shorter lees ageing than the prestige counterpart.",
        "quick": "A straightforward NV Champagne should show brisk mousse, apple/citrus fruit and modest autolytic notes. The quality call hinges on simplicity versus the depth and refinement of the prestige wine beside it.",
        "producer_style": "This bottling acts as the commercial foil in the Champagne pair rather than as a grand marque icon. It is exam-useful precisely because it tests whether the candidate can rank quality inside one region.",
        "why": "Paired with Comtes de Champagne in the all-pairs Paper 3. The task is not just to call Champagne, but to explain why this wine sits lower on the quality ladder and likely has a more commercial market role.",
    },
    "2011_p3_w3": {
        "producer": "Henriques and Henriques",
        "wine_name": "Verdelho 15 Years Old",
        "country": "Portugal",
        "region": "Madeira",
        "sub_region": "Madeira",
        "appellation": "Madeira DOC",
        "classification": "Aged Madeira",
        "style": "fortified",
        "oak": "neutral_old",
        "rs": "medium",
        "profile": "dessert",
        "grape": "Verdelho",
        "technical": "Fortified Madeira matured oxidatively in cask; Verdelho sits in the medium-dry to medium-sweet traditional sweetness band.",
        "quick": "Expect lifted acidity, oxidative nuttiness, citrus peel, caramel and a sweet-savoury finish. Verdelho Madeira sits between the drier Sercial model and the richer Bual/Malmsey register, so balance between acidity and sweetness is central.",
        "producer_style": "Henriques & Henriques is one of Madeira's benchmark specialist houses, especially useful in exams because its age-statement bottlings show the classic grape/sweetness ladder clearly.",
        "why": "This is half of the Madeira pair, designed to test understanding of fortification, oxidative ageing and the traditional varietal sweetness spectrum within one region.",
    },
    "2011_p3_w4": {
        "producer": "Henriques and Henriques",
        "wine_name": "Sercial 10 Years Old",
        "country": "Portugal",
        "region": "Madeira",
        "sub_region": "Madeira",
        "appellation": "Madeira DOC",
        "classification": "Aged Madeira",
        "style": "fortified",
        "oak": "neutral_old",
        "rs": "dry",
        "profile": "dessert",
        "grape": "Sercial",
        "technical": "Fortified Madeira matured oxidatively in cask; Sercial is the driest of the classic noble varieties.",
        "quick": "Sercial Madeira should read drier, more piercing and more citric than the Verdelho alongside it, with high acidity, salty oxidative complexity and a leaner finish.",
        "producer_style": "Henriques & Henriques is a core reference-point producer for classical Madeira styles, making it ideal for internal comparison questions like this pair.",
        "why": "Paired against the older Verdelho to force a candidate to discuss varietal sweetness level, oxidative method and quality differences inside Madeira rather than merely naming the region.",
    },
    "2011_p3_w5": {
        "producer": "The Edge",
        "wine_name": "Pinot Noir",
        "country": "New Zealand",
        "region": "Martinborough",
        "sub_region": "Martinborough",
        "appellation": "Martinborough",
        "classification": "Regional Pinot Noir",
        "style": "still_dry",
        "oak": "unclear",
        "rs": "dry",
        "profile": "medium_balanced",
        "grape": "100% Pinot Noir",
        "technical": "Still red Pinot Noir with Burgundian-inspired handling likely; oak and extraction should be judged from the glass.",
        "quick": "A Martinborough Pinot should show red cherry fruit, savory spice and moderate body with more structure than many lighter New Zealand Pinots. Quality hinges on clarity of site expression and oak integration.",
        "producer_style": "This wine acts as the more modest foil within the Martinborough Pinot pair rather than the benchmark star. The exam value is comparative ranking, not fame recognition.",
        "why": "In the all-pairs Paper 3, wines 5 and 6 ask whether the candidate can recognize same-region Pinot Noir and still separate quality levels between a lesser bottling and a stronger estate benchmark.",
    },
    "2011_p3_w6": {
        "producer": "Escarpment",
        "wine_name": "Pinot Noir",
        "country": "New Zealand",
        "region": "Martinborough",
        "sub_region": "Martinborough",
        "appellation": "Martinborough",
        "classification": "Regional benchmark Pinot Noir",
        "style": "still_dry",
        "oak": "unclear",
        "rs": "dry",
        "profile": "medium_balanced",
        "grape": "100% Pinot Noir",
        "technical": "Serious still Pinot Noir from Martinborough, likely with barrel élevage and more concentration than the comparative foil.",
        "quick": "Escarpment Pinot should show more intensity, finer tannin and a more complete oak/fruit balance than the simpler Pinot beside it. The wine is still red-fruited and savory rather than massive.",
        "producer_style": "Escarpment is one of Martinborough's better-regarded names and therefore a logical benchmark in a regional quality comparison.",
        "why": "This is the stronger half of the Martinborough pair. The candidate needed to call the region and then explain why this wine sits above the more modest Pinot in quality and cellar authority.",
    },
    "2011_p3_w7": {
        "producer": "Fonseca Guimaraens",
        "wine_name": "Vintage Port",
        "country": "Portugal",
        "region": "Douro",
        "sub_region": "Douro / Porto",
        "appellation": "Port",
        "classification": "Vintage Port",
        "style": "fortified",
        "oak": "neutral_old",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Traditional Port varieties",
        "technical": "Fortified during fermentation and bottled for reductive development, contrasting sharply with a cask-aged tawny model.",
        "quick": "Expect concentrated dark fruit, spirit, tannin and youthful-to-mature bottle complexity rather than overt oxidative nut character. Vintage Port should look denser and more structured than the tawny pair-mate.",
        "producer_style": "Fonseca Guimaraens is closely linked to the Fonseca house and serves as a serious Vintage Port reference rather than a simple commercial bottling.",
        "why": "This pair tests the candidate on contrasting Port production paths: bottle-aged Vintage Port versus cask-aged Tawny. The methods and resulting quality expressions are the real exam point.",
    },
    "2011_p3_w8": {
        "producer": "Taylor's",
        "wine_name": "10 Year Old Tawny Port",
        "country": "Portugal",
        "region": "Douro",
        "sub_region": "Douro / Porto",
        "appellation": "Port",
        "classification": "Aged Tawny Port",
        "style": "fortified",
        "oak": "neutral_old",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Traditional Port varieties",
        "technical": "Fortified Port matured oxidatively in cask to an age-statement tawny style.",
        "quick": "Expect nutty, caramel, dried fruit and oxidative complexity with integrated spirit and lower apparent tannin than the Vintage Port beside it. The quality discussion depends on cask-age integration and balance, not raw power.",
        "producer_style": "Taylor's is one of the major classic Port houses and its 10-year tawny is a benchmark commercial reference for the category.",
        "why": "This is the oxidative Port counterweight to the Vintage Port in the pair, designed to test whether the candidate can explain not just style but the production route that created it.",
    },
    "2011_p3_w9": {
        "producer": "Joh. Jos. Prüm",
        "wine_name": "Wehlener Sonnenuhr Kabinett",
        "country": "Germany",
        "region": "Mosel",
        "sub_region": "Wehlen / Wehlener Sonnenuhr",
        "appellation": "Mosel Prädikatswein",
        "classification": "Kabinett",
        "style": "still_sweet",
        "oak": "none",
        "rs": "medium",
        "profile": "dessert",
        "grape": "100% Riesling",
        "technical": "Prädikat Riesling with low alcohol, residual sugar and no botrytis-heavy concentration; sweetness should feel light-footed and acid-driven.",
        "quick": "Classic Mosel Kabinett should show featherweight alcohol, slatey citrus fruit and delicately balanced residual sugar. The key is levity and precision rather than density.",
        "producer_style": "Joh. Jos. Prüm is one of the Mosel's benchmark estates and Wehlener Sonnenuhr is one of its most famous sites, making this a textbook quality reference.",
        "why": "Paired with a Spätlese from another benchmark producer, this wine tests whether the candidate can distinguish Prädikat level and quality within Mosel Riesling rather than just calling Germany.",
    },
    "2011_p3_w10": {
        "producer": "Fritz Haag",
        "wine_name": "Brauneberger Juffer Sonnenuhr Spätlese",
        "country": "Germany",
        "region": "Mosel",
        "sub_region": "Brauneberg / Juffer Sonnenuhr",
        "appellation": "Mosel Prädikatswein",
        "classification": "Spätlese",
        "style": "still_sweet",
        "oak": "none",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "100% Riesling",
        "technical": "Later-picked Prädikat Riesling with more sweetness and richness than Kabinett but still driven by acidity and low alcohol.",
        "quick": "Mosel Spätlese should feel broader, riper and sweeter than Kabinett, with more stone-fruit richness but still a light-footed structure. The candidate needed to discuss sweetness level and quality without confusing it with fully dessert-wine concentration.",
        "producer_style": "Fritz Haag is a major Mosel reference and the Juffer/Juffer Sonnenuhr sites are classic exam territory for quality Riesling.",
        "why": "This is the richer half of the Mosel pair and is there to make the candidate explain the Kabinett/Spätlese distinction through sweetness, concentration and style, not just labels.",
    },
    "2011_p3_w11": {
        "producer": "Domaine du Noble",
        "wine_name": "Loupiac",
        "country": "France",
        "region": "Bordeaux",
        "sub_region": "Loupiac",
        "appellation": "Loupiac AOC",
        "classification": "Botrytised sweet Bordeaux",
        "style": "still_sweet",
        "oak": "unclear",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Semillon / Sauvignon Blanc / Muscadelle likely",
        "technical": "Botrytised sweet wine from the right bank opposite Sauternes, generally less prestigious than top left-bank names.",
        "quick": "Expect honeyed apricot and botrytis-derived sweetness with good acidity, but usually less concentration and layering than top-flight Sauternes. The quality ranking inside the pair matters.",
        "producer_style": "This wine acts as the regional foil to a classed-growth Sauternes rather than as the prestige benchmark. Its value is comparative, not iconic.",
        "why": "The final pair asks the candidate to compare two sweet Bordeaux models from neighboring but unequal appellations. Loupiac is there to test hierarchy and quality calibration against Sauternes.",
    },
    "2011_p3_w12": {
        "producer": "Château Suduiraut",
        "wine_name": "Sauternes",
        "country": "France",
        "region": "Bordeaux",
        "sub_region": "Sauternes",
        "appellation": "Sauternes AOC",
        "classification": "Premier Cru Classé de Sauternes",
        "style": "still_sweet",
        "oak": "new_french",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Semillon-led blend",
        "technical": "Botrytised sweet Bordeaux from a classed growth, with barrel élevage and markedly higher concentration/complexity than a simpler Loupiac.",
        "quick": "A serious Sauternes should show botrytis richness, saffron, apricot, honey and oak-polished depth with high but balancing acidity. Quality should be obvious in length, layering and nobility of fruit.",
        "producer_style": "Suduiraut is one of Sauternes' leading classed-growth estates and is exactly the sort of benchmark bottle an examiner would use to anchor a quality comparison.",
        "why": "This is the benchmark half of the Loupiac/Sauternes pair, included so the candidate must articulate hierarchy, concentration and classed-growth quality rather than just call sweet Bordeaux.",
    },
    "2012_p3_w1": {
        "producer": "Louis Roederer",
        "wine_name": "Brut Vintage",
        "country": "France",
        "region": "Champagne",
        "sub_region": "Champagne",
        "appellation": "Champagne",
        "classification": "Vintage Champagne",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "Classic Champagne blend",
        "technical": "Traditional-method vintage Champagne with longer ageing and more structure than the house NV bottling.",
        "quick": "Vintage Champagne should show more depth, autolysis and seriousness than the NV wine beside it, with tighter structure and a more complete finish.",
        "producer_style": "Louis Roederer is one of Champagne's benchmark houses, and its Vintage bottling is a standard exam-worthy internal quality reference.",
        "why": "In 2012 Paper 3 Question 1, wines 1 and 2 are same producer/same region. This wine is there to anchor the quality and maturity discussion against the NV Brut Premier from the same house.",
    },
    "2012_p3_w2": {
        "producer": "Louis Roederer",
        "wine_name": "Brut Premier",
        "country": "France",
        "region": "Champagne",
        "sub_region": "Champagne",
        "appellation": "Champagne",
        "classification": "Non-vintage Champagne",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "Classic Champagne blend",
        "technical": "Traditional-method NV Champagne built around reserve-wine blending and earlier release than the vintage bottling.",
        "quick": "Brut Premier should feel fresher and more immediately drinkable than the Vintage wine, with less depth but still clear class and technical precision.",
        "producer_style": "Brut Premier was for years Roederer's benchmark NV house bottling, widely used as a reference point for quality non-vintage Champagne.",
        "why": "This is the comparator wine in the same-house Champagne question, forcing the candidate to separate maturity and quality while keeping producer and region constant.",
    },
    "2012_p3_w3": {
        "producer": "Huet",
        "wine_name": "Vouvray Pétillant",
        "country": "France",
        "region": "Loire",
        "sub_region": "Vouvray",
        "appellation": "Vouvray AOC",
        "classification": "Traditional-method sparkling Chenin Blanc",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "100% Chenin Blanc",
        "technical": "Sparkling Chenin from Vouvray, generally made by traditional method with acidity and chalky precision central to style.",
        "quick": "Expect apple, quince and chalk with Chenin's high acidity and a more subtle autolytic profile than Champagne. The appeal case is serious, food-friendly sparkling rather than celebrity fizz.",
        "producer_style": "Huet is one of Vouvray's benchmark estates, so this bottle serves as the serious traditional-method Loire example in the mixed international sparkling set.",
        "why": "In 2012 Paper 3 Question 2 the examiner set four sparkling wines from different countries and different grapes. Huet is the serious Loire Chenin benchmark inside that flight.",
    },
    "2012_p3_w4": {
        "producer": "Jacob's Creek",
        "wine_name": "Sparkling Shiraz",
        "country": "Australia",
        "region": "Australia",
        "sub_region": "South East Australia",
        "appellation": "South Eastern Australia",
        "classification": "Sparkling red",
        "style": "sparkling",
        "oak": "unclear",
        "rs": "medium",
        "profile": "medium_balanced",
        "grape": "Shiraz",
        "technical": "Sparkling red wine, usually tank or Charmat-influenced commercial production rather than prestige traditional-method élevage.",
        "quick": "Sparkling Shiraz should show dark berry fruit, sweetness and mousse rather than autolytic finesse. The candidate needed to place it correctly as an Australian commercial specialty rather than over-romanticise it as classic-method fine wine.",
        "producer_style": "Jacob's Creek is a large commercial Australian brand, making this wine ideal for a question about likely consumer appeal as much as technical identity.",
        "why": "This is the commercial/popular-style foil in the mixed sparkling question. It broadens the candidate's sparkling map beyond Champagne-shaped assumptions.",
    },
    "2012_p3_w5": {
        "producer": "Brancott Estate",
        "wine_name": "Sauvignon Blanc Brut",
        "country": "New Zealand",
        "region": "New Zealand",
        "sub_region": "Marlborough",
        "appellation": "Marlborough",
        "classification": "Aromatic sparkling Sauvignon Blanc",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "Sauvignon Blanc",
        "technical": "Sparkling Sauvignon from Marlborough; the method matters less than the aromatic departure from classical sparkling grapes.",
        "quick": "This should be pungent, grassy and citrusy in a way that immediately breaks from classic Champagne logic. The right answer depends on variety recognition as much as sparkling method discussion.",
        "producer_style": "Brancott Estate is a major Marlborough Sauvignon name, so this wine trades on recognisable regional aroma in an unusual sparkling format.",
        "why": "Included to test whether the candidate can handle unconventional sparkling grape choices and still identify both likely variety and intended market appeal.",
    },
    "2012_p3_w6": {
        "producer": "Beringer",
        "wine_name": "Sparkling Zinfandel Rosé",
        "country": "USA",
        "region": "USA",
        "sub_region": "California",
        "appellation": "California",
        "classification": "Commercial sparkling rosé",
        "style": "rose",
        "oak": "none",
        "rs": "medium",
        "profile": "light_crisp",
        "grape": "Zinfandel",
        "technical": "Commercial sparkling rosé with sweetness and fruit appeal likely more important than traditional fine-sparkling markers.",
        "quick": "Expect overt fruit, pink color and crowd-pleasing sweetness rather than lees complexity. This is a commercial-appeal wine first and an exam trap for candidates who expect all sparkling wines to chase fine-wine seriousness.",
        "producer_style": "Beringer is a well-known California brand, which makes this wine a clean commercial foil in an otherwise more serious or unusual sparkling set.",
        "why": "This wine rounds out the four-country sparkling question by adding a mass-market rosé/commercial-style angle, which candidates had to articulate explicitly in the consumer-appeal part of the stem.",
    },
    "2012_p3_w7": {
        "producer": "Selbach-Oster",
        "wine_name": "Zeltinger Himmelreich Riesling Eiswein 'Junior'",
        "country": "Germany",
        "region": "Mosel",
        "sub_region": "Zeltingen / Himmelreich",
        "appellation": "Mosel Prädikatswein",
        "classification": "Eiswein",
        "style": "still_sweet",
        "oak": "none",
        "rs": "very_sweet",
        "profile": "dessert",
        "grape": "100% Riesling",
        "technical": "Eiswein made from naturally frozen grapes, preserving piercing acidity alongside very high sugar.",
        "quick": "Riesling Eiswein should show crystalline sweetness, very high acidity and concentrated citrus/stone-fruit purity rather than botrytic breadth. The low alcohol and icy precision are key.",
        "producer_style": "Selbach-Oster is a benchmark Mosel estate, making this a credible reference for extreme cool-climate sweet Riesling.",
        "why": "In Question 3, wines 7 and 8 share Riesling but differ radically in sweetness mechanism and likely audience. This is the frozen-grape side of that comparison.",
    },
    "2012_p3_w8": {
        "producer": "Tamar Ridge",
        "wine_name": "Kayena Botrytis Riesling",
        "country": "Australia",
        "region": "Australia",
        "sub_region": "Tasmania",
        "appellation": "Tasmania",
        "classification": "Botrytised sweet wine",
        "style": "still_sweet",
        "oak": "none",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Riesling",
        "technical": "Botrytised dessert wine, contrasting directly with Eiswein in sweetness mechanism, fruit profile and likely texture.",
        "quick": "This should be richer and more botrytic than the Eiswein, with honey/apricot notes and slightly softer shape. The key comparison is noble rot versus frozen-grape concentration using the same grape.",
        "producer_style": "Tamar Ridge is a serious Tasmanian producer, and this bottling functions as the New World botrytis counterpart rather than a simple imitator of German styles.",
        "why": "The examiner built this pair to force method comparison under one grape umbrella. Candidates needed to explain appeal, sweetness balance and production route, not merely say 'sweet Riesling'.",
    },
    "2012_p3_w9": {
        "producer": "Martini",
        "wine_name": "Asti",
        "country": "Italy",
        "region": "Piedmont",
        "sub_region": "Asti",
        "appellation": "Asti DOCG",
        "classification": "Asti",
        "style": "sparkling",
        "oak": "none",
        "rs": "sweet",
        "profile": "light_crisp",
        "grape": "Moscato Bianco",
        "technical": "Tank-fermented sweet sparkling Moscato, generally via the Asti/Charmat process with low alcohol and primary fruit.",
        "quick": "Asti should show grapey Muscat perfume, froth rather than deep mousse, low alcohol and obvious sweetness balanced by freshness. It is the lightest, most playful wine in the all-Muscat question.",
        "producer_style": "Martini is a global commercial brand, which matters here because the wine's market positioning is central to the quality/style discussion.",
        "why": "Question 4 is an all-Muscat flight. Asti is there as the tank-sparkling, low-alcohol expression that candidates had to distinguish from fortified, passito and simple still Moscato styles.",
    },
    "2012_p3_w10": {
        "producer": "Cuvée Réserve",
        "wine_name": "Muscat, Vin Doux Naturel",
        "country": "France",
        "region": "France",
        "sub_region": "Rivesaltes",
        "appellation": "Rivesaltes AOC",
        "classification": "Vin Doux Naturel",
        "style": "fortified",
        "oak": "neutral_old",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Muscat",
        "technical": "Fortified Muscat VDN, where mutage and sweetness retention are more important than sparkling freshness or dried-grape concentration.",
        "quick": "Expect grapey Muscat character with alcohol warmth and fortified sweetness rather than the frothy charm of Asti or the dried-fruit depth of passito. The candidate needed to call fortification clearly.",
        "producer_style": "This bottle functions more as a category marker than a famous-producer benchmark. That is exactly why it is useful in an exam setting.",
        "why": "In the four-wine Muscat question, this is the fortified step on the style ladder and tests whether the candidate can identify VDN production from the glass.",
    },
    "2012_p3_w11": {
        "producer": "Barefoot",
        "wine_name": "Moscato",
        "country": "USA",
        "region": "USA",
        "sub_region": "California",
        "appellation": "California",
        "classification": "Commercial Moscato",
        "style": "still_sweet",
        "oak": "none",
        "rs": "sweet",
        "profile": "light_crisp",
        "grape": "Muscat",
        "technical": "Commercial lightly sweet aromatic wine, likely designed for broad appeal rather than traditional regional typicity.",
        "quick": "This should be simple, fruity and sweet with obvious grapey Muscat character and low structural complexity. The exam point is to recognize it as a commercial style within the Muscat family rather than over-upgrade it.",
        "producer_style": "Barefoot is a mass-market California brand, making this wine the overt commercial foil in the all-Muscat set.",
        "why": "The examiner used this to anchor the consumer/commercial end of the Muscat spectrum. Candidates needed to state quality and style honestly, not dress it up as artisanal fine wine.",
    },
    "2012_p3_w12": {
        "producer": "Donnafugata",
        "wine_name": "Ben Ryé Passito di Pantelleria",
        "country": "Italy",
        "region": "Italy",
        "sub_region": "Sicily / Pantelleria",
        "appellation": "Passito di Pantelleria DOC",
        "classification": "Passito",
        "style": "still_sweet",
        "oak": "none",
        "rs": "very_sweet",
        "profile": "dessert",
        "grape": "Zibibbo (Muscat of Alexandria)",
        "technical": "Passito dessert wine from sun-dried Zibibbo grapes, giving richness and dried-apricot intensity rather than tank-sparkling or fortified style.",
        "quick": "Ben Ryé should be intensely aromatic and sweet with dried apricot, orange peel and Mediterranean herb notes, plus more concentration and nobility than the commercial Moscato in the same set.",
        "producer_style": "Ben Ryé is one of the category's benchmark sweet wines and a classic exam-worthy flagship for passito Muscat.",
        "why": "This is the high-quality anchor in the all-Muscat question. It exists so candidates must discuss not just grape identity but method, concentration and hierarchy across multiple Muscat styles.",
    },
    "2013_p3_w1": {
        "producer": "Valdo",
        "wine_name": "Prosecco Superiore 'Oro Puro'",
        "country": "Italy",
        "region": "Veneto",
        "sub_region": "Valdobbiadene",
        "appellation": "Conegliano Valdobbiadene Prosecco Superiore DOCG",
        "classification": "Prosecco Superiore",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "Glera",
        "technical": "Tank-method sparkling wine where primary fruit and froth matter more than autolytic depth.",
        "quick": "This should read as aromatic, pear-fruited and frothy rather than deeply yeasty or autolytic. It is the accessible commercial end of Italy's sparkling spectrum.",
        "producer_style": "Valdo is a major Prosecco name and a natural commercial benchmark for the category.",
        "why": "In 2013 Paper 3 Question 1, wines 1-3 are all Italian sparkling wines from different regions. This bottle anchors the tank-method Prosecco side of that comparison and helps test commercial potential judgments.",
    },
    "2013_p3_w2": {
        "producer": "Villa Cialdini",
        "wine_name": "Lambrusco Grasparossa di Castelvetro",
        "country": "Italy",
        "region": "Emilia Romagna",
        "sub_region": "Castelvetro",
        "appellation": "Lambrusco Grasparossa di Castelvetro DOC",
        "classification": "Lambrusco",
        "style": "sparkling",
        "oak": "none",
        "rs": "off_dry",
        "profile": "light_crisp",
        "grape": "Lambrusco Grasparossa",
        "technical": "Sparkling red generally made by tank method, with color, froth and fruit sweetness/dryness balance central to the style call.",
        "quick": "Expect purple-red color, soft mousse, dark berry fruit and a lightly bitter, grapey finish. It is stylistically very different from Prosecco and Franciacorta despite belonging to the same broad sparkling paper.",
        "producer_style": "Villa Cialdini is a serious Lambrusco reference and helps lift the category above supermarket stereotypes.",
        "why": "This is the red sparkling outlier inside the all-Italy question. It tests whether the candidate can explain method and quality without defaulting to Champagne-shaped assumptions.",
    },
    "2013_p3_w3": {
        "producer": "Bellavista",
        "wine_name": "Franciacorta Gran Cuvée Brut",
        "country": "Italy",
        "region": "Lombardy",
        "sub_region": "Franciacorta",
        "appellation": "Franciacorta DOCG",
        "classification": "Traditional-method Franciacorta",
        "style": "sparkling",
        "oak": "none",
        "rs": "dry",
        "profile": "light_crisp",
        "grape": "Chardonnay / Pinot Noir likely",
        "technical": "Traditional-method sparkling wine with lees ageing, positioned as Italy's fine-wine answer to Champagne rather than a tank-method style.",
        "quick": "Franciacorta should show finer mousse, more autolysis and more structural seriousness than the Prosecco or Lambrusco. The quality call depends on precision and method-derived complexity.",
        "producer_style": "Bellavista is one of Franciacorta's leading houses and functions as a benchmark in the category.",
        "why": "This is the fine-wine anchor in the three-Italian-sparkling question, set against more commercial and stylistically different domestic sparklers.",
    },
    "2013_p3_w4": {
        "producer": "Tyrrell's",
        "wine_name": "Vat 1 Semillon",
        "country": "Australia",
        "region": "Hunter Valley",
        "sub_region": "Hunter Valley",
        "appellation": "Hunter Valley GI",
        "classification": "Benchmark dry Semillon",
        "style": "still_dry",
        "oak": "none",
        "rs": "dry",
        "profile": "medium_balanced",
        "grape": "100% Semillon",
        "technical": "Low-alcohol dry Semillon made without obvious oak and relying on bottle age for complexity.",
        "quick": "Expect wax, toast and lemon-curd development in a light-bodied frame. This is a textbook mature Hunter Semillon reference.",
        "producer_style": "Tyrrell's Vat 1 is one of Australia's classic white benchmarks and an ideal exam foil in blend-composition or same-grape comparison sets.",
        "why": "In Question 2, one grape variety is common to wines 4-6 in varying proportions. Vat 1 is the pure Semillon reference point against the Bordeaux dry white wines that follow.",
    },
    "2013_p3_w5": {
        "producer": "Château Villa Bel Air",
        "wine_name": "Blanc",
        "country": "France",
        "region": "Bordeaux",
        "sub_region": "Graves",
        "appellation": "Graves AOC",
        "classification": "Dry white Bordeaux",
        "style": "still_dry",
        "oak": "unclear",
        "rs": "dry",
        "profile": "medium_balanced",
        "grape": "Semillon / Sauvignon Blanc blend",
        "technical": "Dry white Bordeaux where Semillon is blended with Sauvignon Blanc; oak and lees work likely play a role.",
        "quick": "Expect citrus, orchard fruit and some oak/lees texture. This wine sits between pure Semillon and sweet Sauternes in the three-wine Semillon thread.",
        "producer_style": "Villa Bel Air is a classic Graves estate, suitable as a middle-ground dry Bordeaux example in a grape-composition question.",
        "why": "This is the dry Bordeaux blend in the Question 2 trio. It tests whether the candidate can trace one common grape across a pure-varietal Semillon, a dry Bordeaux blend and a sweet Sauternes second wine.",
    },
    "2013_p3_w6": {
        "producer": "Castelnau de Suduiraut",
        "wine_name": "Castelnau de Suduiraut",
        "country": "France",
        "region": "Bordeaux",
        "sub_region": "Sauternes",
        "appellation": "Sauternes AOC",
        "classification": "Sweet Bordeaux second wine",
        "style": "still_sweet",
        "oak": "new_french",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Semillon-led blend",
        "technical": "Botrytised sweet wine from Suduiraut's second label, with Semillon central but sweetness and noble rot changing the profile entirely.",
        "quick": "Expect botrytis richness, apricot, saffron and sweetness with oak-polished texture. The point is to recognize shared Semillon DNA across radically different expressions.",
        "producer_style": "As the second wine of Suduiraut, Castelnau gives real Sauternes credentials at a slightly less lofty level than the grand vin.",
        "why": "This is the sweet end of the Question 2 Semillon thread, asking candidates to compare how one grape can behave as pure dry varietal, dry blend component and noble-rot sweet-wine base.",
    },
    "2013_p3_w7": {
        "producer": "Dr Loosen",
        "wine_name": "Ürziger Würzgarten Riesling Kabinett",
        "country": "Germany",
        "region": "Mosel",
        "sub_region": "Ürzig / Würzgarten",
        "appellation": "Mosel Prädikatswein",
        "classification": "Kabinett",
        "style": "still_sweet",
        "oak": "none",
        "rs": "medium",
        "profile": "dessert",
        "grape": "100% Riesling",
        "technical": "Low-alcohol Prädikat Riesling with residual sugar balanced by acidity rather than botrytic density.",
        "quick": "Expect delicate sweetness, slate-influenced fruit and very low alcohol. It is the lightest and least concentrated of the six-wine sweet/non-fortified mixed bag.",
        "producer_style": "Dr Loosen is a benchmark Mosel estate and a natural exam reference for Prädikat Riesling.",
        "why": "Question 3 mixes six sweet or sugar-bearing non-fortified wines from different countries. This wine is there to represent classic lightly sweet German Riesling rather than a full dessert style.",
    },
    "2013_p3_w8": {
        "producer": "Château Jolys",
        "wine_name": "Cuvée Jean Jurançon",
        "country": "France",
        "region": "South West France",
        "sub_region": "Jurançon",
        "appellation": "Jurançon AOC",
        "classification": "Sweet Jurançon",
        "style": "still_sweet",
        "oak": "none",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Petit Manseng likely",
        "technical": "Late-harvest or passerillage-driven sweet wine where acidity and exotic fruit are key to style.",
        "quick": "Jurançon should show pineapple, mango, citrus and bright acidity rather than botrytic heaviness. It is a sweet wine, but with a very different aromatic profile from Sauternes or Tokaji.",
        "producer_style": "Château Jolys is a known Jurançon estate and works well as a category marker for the region's high-acid sweet wines.",
        "why": "This wine broadens the sweet-wine map in Question 3 beyond botrytis and frozen-grape models. The candidate needed to identify style from acidity and fruit profile, not just sweetness level.",
    },
    "2013_p3_w9": {
        "producer": "Royal Tokaji",
        "wine_name": "Tokaji 5 Puttonyos Aszú",
        "country": "Hungary",
        "region": "Tokaj",
        "sub_region": "Tokaj",
        "appellation": "Tokaji",
        "classification": "5 Puttonyos Aszú",
        "style": "still_sweet",
        "oak": "neutral_old",
        "rs": "very_sweet",
        "profile": "dessert",
        "grape": "Furmint / Hárslevelű likely",
        "technical": "Botrytised Tokaji made from aszú berries, with high sweetness, high acidity and oxidative/ageing nuance depending on élevage.",
        "quick": "Expect apricot, marmalade, botrytis spice and vibrant acidity. Tokaji should feel nobler and more acid-driven than many soft sweet wines of similar sweetness.",
        "producer_style": "Royal Tokaji is a benchmark modern producer and a classic exam reference for Tokaji Aszú.",
        "why": "This is the Hungarian benchmark in the six-country sweet-wine mixed bag, asking the candidate to separate botrytised Tokaji from BA, ice wine, Vin Santo and lightly sweet Riesling.",
    },
    "2013_p3_w10": {
        "producer": "Alois Kracher",
        "wine_name": "Cuvée Beerenauslese",
        "country": "Austria",
        "region": "Burgenland",
        "sub_region": "Burgenland",
        "appellation": "Burgenland Prädikatswein",
        "classification": "Beerenauslese",
        "style": "still_sweet",
        "oak": "none",
        "rs": "very_sweet",
        "profile": "dessert",
        "grape": "Source needed",
        "technical": "Botrytised Austrian Prädikat sweet wine, usually richer and more concentrated than Kabinett but different in profile from Tokaji or ice wine.",
        "quick": "Beerenauslese should show botrytic sweetness, ripe orchard/tropical fruit and ample concentration, but without the frozen-grape purity of ice wine.",
        "producer_style": "Alois Kracher is one of Austria's iconic sweet-wine names, making this a very exam-plausible benchmark bottle.",
        "why": "This is the Austrian botrytis reference in Question 3, intended to test whether the candidate can distinguish BA from other concentrated sweet-wine mechanisms.",
    },
    "2013_p3_w11": {
        "producer": "Peller Estate",
        "wine_name": "Vidal Ice Wine",
        "country": "Canada",
        "region": "Canada",
        "sub_region": "Niagara Peninsula",
        "appellation": "VQA Niagara Peninsula",
        "classification": "Icewine",
        "style": "still_sweet",
        "oak": "none",
        "rs": "very_sweet",
        "profile": "dessert",
        "grape": "Vidal",
        "technical": "Icewine from naturally frozen grapes, with high sugar and piercing acidity but without botrytic complexity as the main driver.",
        "quick": "Expect concentrated sweetness, candied citrus/tropical fruit and crystalline acidity. The key distinction is frozen-grape concentration rather than noble rot or oxidative handling.",
        "producer_style": "Peller Estate is one of Canada's best-known icewine producers and a straightforward exam reference for the category.",
        "why": "This wine gives the candidate a classic North American icewine marker inside the six-country sweet-wine mixed bag.",
    },
    "2013_p3_w12": {
        "producer": "Capezzana",
        "wine_name": "Vin Santo",
        "country": "Italy",
        "region": "Italy",
        "sub_region": "Tuscany",
        "appellation": "Vin Santo del Carmignano / Toscana",
        "classification": "Vin Santo",
        "style": "oxidative",
        "oak": "neutral_old",
        "rs": "sweet",
        "profile": "dessert",
        "grape": "Trebbiano / Malvasia likely",
        "technical": "Passito/oxidative sweet wine from dried grapes aged in small casks, making it structurally and aromatically distinct from botrytis or icewine models.",
        "quick": "Expect amber-gold color, dried fruit, nuts, caramel and oxidative complexity rather than fresh botrytic fruit. The method is the key differentiator.",
        "producer_style": "Capezzana is a respected Tuscan estate, and its Vin Santo is a strong category marker for oxidative Italian sweet wine.",
        "why": "This is the oxidative/dried-grape counterpoint in the six-country non-fortified sweet-wine mixed bag, forcing the candidate to identify a very different sweetness mechanism from the other wines in the set.",
    },
}


QUESTION_TEXT = {
    "2011_p3": "Wines 1 to 12 are all presented in pairs: 1&2, 3&4, 5&6, 7&8, 9&10, 11&12. Each pair is from a single region of origin.",
    "2012_p3_q1": "Wines 1 and 2 are from the same region and same producer.",
    "2012_p3_q2": "Wines 3-6 are each from a different country. Each is made predominantly from a different, single grape variety.",
    "2012_p3_q3": "Wines 7 and 8 are from different countries. Each is made from the same, single grape variety.",
    "2012_p3_q4": "Wines 9-12 are all made from the same, single grape variety.",
}


def search_url(text: str) -> str:
    return f"https://www.wine-searcher.com/find/{quote_plus(text)}"


def ddg_url(text: str) -> str:
    return f"https://duckduckgo.com/?q={quote_plus(text)}"


def why_text(wine_id: str, base: str) -> str:
    if wine_id.startswith("2011_p3"):
        return f"Used in 2011 Paper 3. The stem begins: \"{QUESTION_TEXT['2011_p3']}\" {base}"
    slot = int(wine_id.split("_w")[1])
    qkey = "2012_p3_q1" if slot <= 2 else "2012_p3_q2" if slot <= 6 else "2012_p3_q3" if slot <= 8 else "2012_p3_q4"
    return f"Used in 2012 Paper 3. The stem begins: \"{QUESTION_TEXT[qkey]}\" {base}"


def render(entry_id: str, meta: dict) -> str:
    abv = Path(RESEARCH_DIR / f"{entry_id}.md").read_text(encoding="utf-8").split("abv: ", 1)[1].splitlines()[0].strip()
    title = f"{meta['wine_name']}, {meta['producer']}"
    query = f"{meta['producer']} {meta['wine_name']} {meta['region']} {abv}"
    return f"""---
wine_id: {entry_id}
producer: {meta['producer']}
wine_name: {meta['wine_name']}
vintage: {Path(RESEARCH_DIR / f"{entry_id}.md").read_text(encoding="utf-8").split("vintage: ", 1)[1].splitlines()[0].strip()}
country: {meta['country']}
region: {meta['region']}
sub_region: {meta['sub_region']}
appellation: {meta['appellation']}
abv: {abv}
classification: {meta['classification']}
related_wines: []
sources:
  - {search_url(query)}
  - {ddg_url(query)}
last_updated: 2026-05-26
style_category: {meta['style']}
oak_signature: {meta['oak']}
rs_level: {meta['rs']}
structural_profile: {meta['profile']}
---

# {title}

## Quick tasting profile
{meta['quick']}

## Technical specs
- Grape variety: {meta['grape']}
- Vineyard: Source needed
- Soils: Source needed
- Vinification: {meta['technical']}
- Élevage: Source needed
- ABV / RS / TA: {abv}% / Source needed / Source needed

## Vintage character
Source needed for a vintage-specific note on this exact release. In exam use, calibrate from the glass: fruit ripeness, acidity, tertiary development and concentration matter more than overclaiming historical weather detail.

## Producer style
{meta['producer_style']}

## Why it's in this exam
{why_text(entry_id, meta['why'])}

## Sources
- [Wine-Searcher query]({search_url(query)}) - entry point for exact bottling, availability and merchant references
- [DuckDuckGo query]({ddg_url(query)}) - entry point for producer, cuvée and vintage lookups
- Source needed for bottling-specific technical detail beyond what is safely inferable from category, producer and exam context
"""


def main() -> None:
    updated = 0
    for entry_id, meta in ENTRIES.items():
        path = RESEARCH_DIR / f"{entry_id}.md"
        path.write_text(render(entry_id, meta), encoding="utf-8")
        updated += 1
    print(f"OK: updated {updated} weak Paper 3 briefs")


if __name__ == "__main__":
    main()
