import { neon } from "@neondatabase/serverless";
import { requireApiKey } from "@/lib/api-key";
import { generateSanitizedTastingNotes, type TastingWine } from "@/lib/tasting";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 120;

/**
 * GET /api/stem-sniper/notes?questionId=
 * Reverse Tasting — Stage 2 (Layer B). Returns the sanitized in-glass sensory notes for a drill's
 * wines, generated by the SAME generator the study page uses. The wines are loaded server-side and
 * NEVER returned; only per-slot notes with variety/region/origin giveaways stripped.
 */
export async function GET(request: Request) {
  const keyResult = await requireApiKey(request);
  if (keyResult instanceof Response) return keyResult;

  const { searchParams } = new URL(request.url);
  const questionId = searchParams.get("questionId");
  if (!questionId) return Response.json({ error: "questionId required" }, { status: 400 });

  const sql = neon(process.env.DATABASE_URL!);
  const rows = await sql`SELECT wines FROM generated_questions WHERE question_id = ${questionId}`;
  const r = rows[0];
  if (!r) return Response.json({ error: "question not found" }, { status: 404 });

  const wines = (typeof r.wines === "string" ? JSON.parse(r.wines) : r.wines) as TastingWine[];
  if (!Array.isArray(wines) || wines.length === 0) {
    return Response.json({ error: "no wines for question" }, { status: 400 });
  }

  const notes = await generateSanitizedTastingNotes({
    wines,
    questionId,
    apiKey: keyResult.apiKey,
    source: keyResult.source,
    userId: keyResult.user.id,
  });

  return Response.json({ notes: wines.map((w, i) => ({ slot: w.slot, note: notes[i] || "" })) });
}
